### ISSUE TITLE
V1.19.1 some bugs

### ISSUE THREAD

**Issue by oschwartz10612** [Prestonjf/scorecenter#1]
Hello,

I just wanted to let you know that this is a fantastic web application! It does everything I could ever hope that it would do and I am investigating it for one of our next year's tournament.

I don't know if this is under development anymore, but I have found a few bugs.

1. When you log in, the "Information" pane displays "echo '>'.getRoleName($role).'" in the dropdown box.
2. Anywhere where you should be able to manage users does not appear to work. I have played with the dropdowns and it does not display any users. Creating users works, but you can not see anywhere what users are in the system.
3. The coach login does not display the tournament. You can select it from the dropdown, but it does not show up in the table.
4. The generate slideshow button does not appear to work. Maybe it is because I only have one test event in the system.
5. After an event has been submitted and verified, the complete red x does not go away.

Maybe I am using a newer version of PHP?

Again, this is a revolutionary piece of software that is so generous to make open source. If this is user error, I apologize.

Thanks,
Owen

**Comment by oschwartz10612** [comment]
Is my issue isolated or have you been able to recreate the bugs?

**Comment by Prestonjf** [comment]
Hi Owen, I appreciate you taking the time to look at the Score Center application.

It's possible I do not have the most up to date database schema uploaded, which may be causing some of the problems. I have an instance of Score Center running on a server with PHP 7.1, which most Science Olympiad Tournaments in Michigan are using. 

We are not experiencing issues 1 thru 4. Issue 5 is a known issue. I believe if you click the tournaments tab, and click "Enter Scores" to return to the Tournament Events screen, the completed events should be reflected (showing a green check then). The screen is just not being refreshed after saving a verified and submitted event.

I am currently standing up a new instance from the latest code and latest db schema to confirm functionality and if the issues you mentioned are occurring. If I don't see any issues, I will upload the latest db schema and any new code changes, and ask that you setup a new instance from that.

**Comment by oschwartz10612** [comment]
That sounds great! Thanks for taking the time to help me out.

**Comment by Prestonjf** [comment]
Using the current code and up-to-date database, the application seemed to be performing correctly. 

Hopefully the database is where your problem is at. I have bumped the version on the code and pushed version 1.19.1 to GitHub. I reorganized the repository slightly, but it should make sense. The new db schema is in the database folder, and the application code is in the scorecenter folder. Please try importing the new db schema again, and use a new copy of the application code. Default username:password is admin:admin. Let me know if you still experience issues 1-4. I did not work on issue 5 just yet.

Also note, I have uploaded a Tournament Score Center User Guide PDF, which (is a work in progress) but contains information on each page of the application, which may be helpful.

**Comment by oschwartz10612** [comment]
Okay, so I created a new instance and installed the new database file and code.

I believe I am still getting all of the same issues as before.

Maybe there is something wrong on my end? These are the steps I have taken:

- Placed the scorecenter files into /var/www/html on an apache server with php
- I am using PHP Version 7.2.10-0ubuntu0.18.04.1
- Installed mysql on the server and added the database file to the score_center_db database I created
- Created a user for the database and linked it in the login.php file

The database is populated with the following tables

+---------------------------+
| Tables_in_score_center_db |
+---------------------------+
| EVENT                     |
| REF_DATA                  |
| SCHEDULE_EVENT            |
| SCHEDULE_EVENT_PERIOD     |
| SCHEDULE_PERIOD           |
| SCHEDULE_TEAM             |
| TEAM                      |
| TEAM_COACH                |
| TEAM_EVENT_SCORE          |
| TOURNAMENT                |
| TOURNAMENT_EVENT          |
| TOURNAMENT_SCHEDULE       |
| TOURNAMENT_TEAM           |
| TOURNAMENT_VERIFIER       |
| USER                      |
| USER_LOGIN_LOG            |
| USER_ROLE                 |
+---------------------------+

I know that is brief, but is there anything that stands out? 

Apologies,
Owen

**Comment by Prestonjf** [comment]
The steps you used to setup the application seems correct. The database schema looks like it imported properly. If you can log in and create a tournament/events/teams, then the application is connected to the db fine. I updated my PHP version to 7.2.11 and the application was running OK. I am using Chrome browser.

You can look at the instance I just setup here with default credentials. (I will probably change them in a few days)
http://scorecenter.prestonsproductions.com/scorecenter/logon.php

If you want to compare my PHP configuration, I have phpinfo() printed on the home page. (index.php) The page styling is altered because that is printed. I hope this can help you troubleshoot your issues.

**Comment by oschwartz10612** [comment]
I did a completely fresh install and I am getting the same result. The fact that the db connects and I am getting echo '>'.getRoleName($role). still makes me think it is a PHP issue.

This is my php info: https://drive.google.com/open?id=16opt4jWnZFZb_5CBvcAutaVeIWRrTS3t

I am also on Chrome. Should I try on Debian 9 insted of Ubuntu 18.04?

Edit: I tried Debian and got the same result. Maybe it is Apache? 

Edit 2: I tried Nginx. Did not work. I'm at a loss at this point.

Owen

**Comment by Prestonjf** [comment]
If you were able to use the link to the application I have setup and you did not get the same errors, it is most likely a PHP configuration issue. I don't think changing the OS will have an effect.

In that case you may want to compare what libraries inside php are installed. I printed out phpinfo on the index.php page which will tell you what libraries I have installed. I will check later to compare your phpinfo.

Also, I think you can turn Notices/Debug alerts on in PHP. Maybe after turning that on, it will tell you where an error might be.

Preston

**Comment by oschwartz10612** [comment]
I was able to look through the php info on the site, but PHP it not my expertise so I was not aware that there were libraries I had to install.

I will take a look tomorrow.

Edit: I have absolutely no idea what I am looking at. I tried to do some Googleing and go nowhere. Them I tried to mess around with the ./configure command but also got nothing.

Thanks again for all of your help,
Owen

**Comment by Prestonjf** [comment]
Sorry to hear that you are still experiencing issues. It has been a while since I have worked with PHP and the server configuration. I thought the default PHP configuration should be adequate.

echo '>'.getRoleName($role). should not be printed out on the screen, so that makes me think something is causing an error when rendering the page. Could you share the page source of the index.php page? (right click and view page source)

I did notice a few PHP modules installed on my server vs. yours. I don't know if they will improve the issues you are having but here they are: bcmath, bz2, zip. I think bz2 might be important. 
For each library:
1. Install the module: apt-get install php7.2-bz2
2. Enable the module in PHP.ini: extension = "bz2.so" 
3. Restart Apache: /etc/init.d/httpd restart

I also mentioned turning on Notices and Error messages. So when you load the pages, errors should print out. Setting the value to E_ALL should print out all warnings, and notices. You might find something there causing the problem.
1. Modify this property in PHP.ini: error_reporting = E_ALL
2. Restart Apache.

Preston

**Comment by oschwartz10612** [comment]
Okay. I will give all of that a try. Thanks!

**Comment by oschwartz10612** [comment]
Okay so I have installed the libraries but I am still getting the same issues. PHP info: https://drive.google.com/open?id=1AFCR7LPmz50DkZD-MbaJJh09ssAWJeN8

I enabled error reporting, but I am not sure where the errors would appear? 

Owen

**Comment by Prestonjf** [comment]
The errors, warnings and notices should display at the top of the screens I think. I guarantee there should be some (at least Notices). I haven't turned those on in a while. After searching, "display_errors = On" should perhaps be set in PHP.ini as well.

Could you post the page source of index.php to a file on Google Drive, so I can see the output you are getting?

**Comment by oschwartz10612** [comment]
Index.php: https://drive.google.com/open?id=16RT-T9ecqX9lAg6xLj2N6yhy_tlSx9JD (sorry about that)

I tried turning display_errors = On and I didn't get anything.

Sorry for the hassle!

**Comment by Prestonjf** [comment]
Actually, I would like the html that is printed out once you log in to the application. So view page source of the "home" page then copy all the text into a file. I am interested to see what the php code printed out. No Worries.

**Comment by oschwartz10612** [comment]
Oh, okay. Here: https://drive.google.com/open?id=1MNjlV2FvWP0IhOllkTN_7mKLEE2_PZ8w

Also, I installed all of the extra libraries you had so the new PHP info: https://drive.google.com/open?id=18HQiUeTf5m4OEt_IJpP9yx8hSyhkn6tl

Edit: Adding the rest of the libraries did not seem to help.

**Comment by Prestonjf** [comment]
My Apologies, you posted what I needed before. Interestingly enough, there was a block of PHP code that was printed out in the html instead of being executed.

```
<? foreach ($userSessionInfo->getAvailableRoles() as $role) {
    echo '<option value="'.$role.'" ';
    if ($role == $userSessionInfo->getRole()) echo 'selected';
    echo '>'.getRoleName($role).'</option>';
} ?>
```
In the actual index.php file, could you change:
"<?" to "<?php"

And try loading the application. And let me know if the problem is still on the home screen.

**Comment by oschwartz10612** [comment]
Hey! There we go! That worked!

That is bizarre because I did use the updated release.

I just checked the users though, and apparently, that is still also not working. So issues 2 and 3 still persist.

**Comment by Prestonjf** [comment]
Great to hear!

After some research, it looks like the syntax "<?" is deprecated and "<?php" is the accepted way to go. I  think previous PHP versions "<?" was OK and for some reason my server configuration must not have a problem with them. I will need to go through the code and make sure I update any of these I find.

This could also be the problem for the issues 2 and 3. Could you tell me the php file where they are occurring for you?

For Issue 2, do you see the users on the "Manage User" page?

**Comment by oschwartz10612** [comment]
https://drive.google.com/open?id=1OWjYSqyU3folIDf9e884iQnxJ240nmY3 and https://drive.google.com/open?id=1pCjUT-NO2Oe9STMbK_89ByhJl3Mvzsha

I assume anything else may also be caused by that, so I can weight for you to review everything.

Hopefully, this has been some help! :}

**Comment by Prestonjf** [comment]
For the coach login issue, can you confirm you have:
1. Created a Team
2. Created a coach user and it displays as linked to the team on the team_detail.php page
3. Created a Tournament and linked that team to the tournament.

**Comment by oschwartz10612** [comment]
Yes. I have done all of those things. 

Again, I can select my tournament from the dropdown and select the date but when I press search it does not come up. Same thing essentially for the users.

**Comment by Prestonjf** [comment]
There is most likely a different cause for this bug (#3). It seems to me that some PHP code is not being run towards the bottom of the file. It may be throwing an error. (/var/log/httpd/error_log ?)

Also, you can add the following lines at the top of index.php which should show errors for that page when you load it. Please add these lines under line 1, run login, and let me know if/what errors you receive.

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

**Comment by oschwartz10612** [comment]
/var/log/httpd/error_log does not exist.

For the errors I got:

Warning: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in /var/www/html/logon_check.php on line 44

Warning: Use of undefined constant HTTP_HOST - assumed 'HTTP_HOST' (this will throw an Error in a future version of PHP) in /var/www/html/logon_check.php on line 53

And at the bottom:

Notice: Undefined index: savesuccessScore in /var/www/html/index.php on line 373

Notice: Undefined index: accountCreationSuccess in /var/www/html/index.php on line 377

Notice: Undefined index: accountUpdateSuccess in /var/www/html/index.php on line 381

Notice: Undefined index: savesuccessUtilities in /var/www/html/index.php on line 384

Sorry, last edit. For the coach I get this above the table:

Notice: Undefined index: userEventDate in /var/www/html/index.php on line 328

Notice: Undefined index: userTournament in /var/www/html/index.php on line 334

**Comment by oschwartz10612** [comment]
For users.php I get:


Warning: Use of undefined constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in /var/www/html/logon_check.php on line 44

Warning: Use of undefined constant HTTP_HOST - assumed 'HTTP_HOST' (this will throw an Error in a future version of PHP) in /var/www/html/logon_check.php on line 53

Warning: Use of undefined constant PAGEROWS - assumed 'PAGEROWS' (this will throw an Error in a future version of PHP) in /var/www/html/functions/pagination.php on line 26

and:

Notice: Undefined index: savesuccessUser in /var/www/html/user.php on line 170

**Comment by Prestonjf** [comment]
Thanks for capturing those messages. The warnings and notices should be OK and not be causing the problem. 

Please add this line at the bottom of index.php and let me know what the output is after running:
```
<?php 
	echo 'MYSQLI ERROR: ' . $mysqli->error;
?>
```

**Comment by oschwartz10612** [comment]
It just says MYSQLI ERROR:

**Comment by oschwartz10612** [comment]
Wait. Sorry I had to log in as a coach. This is what it says:

MYSQLI ERROR: Expression #1 of ORDER BY clause is not in SELECT list, references column 'score_center_db.T.DATE' which is not in SELECT list; this is incompatible with DISTINCT

Edit: I get nothing on the user.php page.

**Comment by Prestonjf** [comment]
OK. Progress. I think this might be a version issue with MySQL. I think I am running 5.6. You may have a newer version.

I am going to update index.php on github. Please take the new file from the repository and use that in your project. Let me know if the tournament loads once logging in as a coach.

**Comment by oschwartz10612** [comment]
Success! Loads like a charm.

I think we are down to the users and the slideshow now.

Thanks for all of the hard work!

**Comment by Prestonjf** [comment]
I added some error logging. Please update Controller.php and user.php from the repository. Then login and go to manage user. Hopefully a "MySQLi" error is printed there. Let me know.

**Comment by oschwartz10612** [comment]
It does not show an error

Sorry for the delay

**Comment by oschwartz10612** [comment]
Also, I just learned that on the index page when logged in as a super user, the tournament does not come up when you change to the other user groups. If I log in as them though, it does work.

Would it just be easier to roll back mysql?

**Comment by Prestonjf** [comment]
If you are able to try MySQL 5.6, that may be a good test. I think we would both be on the same versions then. 

Depending on the role you are logged in as, will determine how the screens (including index.php) displays. I think Super User and Admin just display Today's Tournaments. (Tournament on todays date)

**Comment by oschwartz10612** [comment]
Okay. I will get on that as soon as a get a chance.

**Comment by oschwartz10612** [comment]
Okay. I guess I installed 5.7 but I assume it is close. Now on the user page, I am getting this:

MYSQLIi Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'score_center_db.U.USER_ID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

Also now the coach login is not working.

**Comment by Prestonjf** [comment]
I will try to take a look at this tomorrow. I probably can fix the user.php SQL error. Pretty sure the errors are due to some queries not being compatible with mysql5.7.

Does the coach login, fail to login? Or is there another error after login?

Is the view slideshow button going to the slideshow page where you can navigate with the arrow keys?

Thanks for taking the time to look into this.

**Comment by oschwartz10612** [comment]
For the slideshow, it changes pages to /controller.php?viewSlideShow= but says "This page isn’t working 35.245.239.239 is currently unable to handle this request. HTTP ERROR 500"

I felt like we were going backward with 5.7, and why work on an old version? I went back to the newest version. Sorry!

Now the coach thing works again but oddly I am now getting the same error in the user.php file.

Hope that helps,
Owen

**Comment by Prestonjf** [comment]
Thanks for the update. After going back to the newest version, what is the MySQL version number?

The same error may exist on user.php. I will check it out tomorrow.

**Comment by oschwartz10612** [comment]
Ver 14.14 Distrib 5.7.24

I guess I didn't do much! 😂

Part of the issue is that I could not find 5.6 for Ubuntu 18.04.

**Comment by Prestonjf** [comment]
I have updated Controller.php in the repository. I am trying an updated query. Please take the new file and put it into your project. Then try to load the user.php. Let me know if you get an error or it works.

**Comment by oschwartz10612** [comment]
Okay. I will have to try it this afternoon at around 3. My apologies!

**Comment by oschwartz10612** [comment]
Okay. The new controller.php fixed the users! 

So we are down to the slideshow (view and export) I think.

As smaller issues, I have noticed that what you recommended before to fix the "Completed" checkbox thing has not worked. The box is always red no matter what. Also on index.php when I cycle through the different users the tournament does not show up.

We are making progress! Thanks for all of the help!

**Comment by Prestonjf** [comment]
Great news!

1. What happens when you click the "View Slideshow" button? Are you taken to a new page? When you click "Export Slideshow" No pdf downloads?

2. On the "Enter Scores" screen, the Completed column still displays a red X, even though All teams are scored and submitted and verified columns have a green check?

3. On index.php, by cycling users, do all users have the same role? I believe only a Coach or Supervisor Role will display all tournaments linked to them. Roles of Super User, Admin or Verifier will only show tournaments occurring on today's date.

**Comment by oschwartz10612** [comment]
1. When I click the buttons it takes me to a new page that has /controller.php?viewSlideShow= and /controller.php?exportSlideShowPDF= as the url. Does it look like maybe whatever the get variable should be is not getting passed? Both pages say "This page isn’t working *ip* is currently unable to handle this request. HTTP ERROR 500" in Chrome.

2. Yes. I have tried logging out and logging in, clicking the homepage then going back, etc. I have tried with more than one event and more than one team and I get the same issue I think. It also shows up if you log in as other users.

3. I changed the tournament to occur today. The Admin and Super User roles show it, but the Verifier does not. The Coach and the Supervisor also do now show it when you search or anything. If I log in as any user it works.

**Comment by Prestonjf** [comment]
1. Can you add the following lines under line 1 of Controller.php and let me know what happens when trying to click "View Slideshow"?
```
error_reporting(E_ALL);
ini_set('display_errors', 'On');
```

2. The teams scored out of total teams needs to be the same, so if you have 10 total teams, 10/10 should be there. If you have 2/10, The system thinks the event is not completed yet. You can change total amount of teams in "Manage Tournament".

3. In "Manage Tournament" (at the bottom of the page) make sure there is a user linked in the "Verifiers" section. When this is linked and you login as that user, the tournament should show up on index.php.

**Comment by oschwartz10612** [comment]
1. The errors from controller.php are attached. 
[errors.txt](https://github.com/Prestonjf/scorecenter/files/2761637/errors.txt)

2. I will try this later as now it is throwing notices every time I try to edit the tournament and not working, but it sounds like that is my fault. Sorry!

3. Yes, when I log in as a Verifier it works, just not when I select it as a Super User. The coach and the supervisor dont work in the dropdown, but again, that is a minor thing and I don't know if it really matters.

**Comment by Prestonjf** [comment]
1. Thanks for the output. Can you add this line in Controller.php at Line 3587 . which is right after $results = $mysqli->query($query);

`echo 'mysqli error: ' . $mysqli->error;`

2. The notices are coming from the error logging we put in Controller.php. Once we take that out it should be fine.

**Comment by oschwartz10612** [comment]
I got the following output:


Notice: Undefined index: command in /var/www/html/controller.php on line 65

Notice: Undefined index: command in /var/www/html/controller.php on line 70

Notice: Undefined index: command in /var/www/html/controller.php on line 77

Notice: Undefined index: command in /var/www/html/controller.php on line 99

Notice: Undefined index: command in /var/www/html/controller.php on line 111

Notice: Undefined index: command in /var/www/html/controller.php on line 116

Notice: Undefined index: command in /var/www/html/controller.php on line 124

Notice: Undefined index: command in /var/www/html/controller.php on line 133

Notice: Undefined index: command in /var/www/html/controller.php on line 146

Notice: Undefined index: command in /var/www/html/controller.php on line 150

Notice: Undefined index: command in /var/www/html/controller.php on line 156

Notice: Undefined index: command in /var/www/html/controller.php on line 163

Notice: Undefined index: command in /var/www/html/controller.php on line 308

Notice: Undefined index: command in /var/www/html/controller.php on line 319

Notice: Undefined index: command in /var/www/html/controller.php on line 324

Notice: Undefined index: command in /var/www/html/controller.php on line 329

Notice: Undefined index: command in /var/www/html/controller.php on line 334

Notice: Undefined index: command in /var/www/html/controller.php on line 346

Notice: Undefined index: command in /var/www/html/controller.php on line 355

Notice: Undefined index: command in /var/www/html/controller.php on line 367

Notice: Undefined index: command in /var/www/html/controller.php on line 422

Fatal error: Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/html/controller.php:3593 Stack trace: #0 /var/www/html/controller.php(498): loadSlideShow('', Object(mysqli)) #1 {main} thrown in /var/www/html/controller.php on line 3593

**Comment by oschwartz10612** [comment]
Wait! Sorry I think I put it in the wrong line! Stupid nano!

This is the output:

Notice: Undefined index: command in /var/www/html/controller.php on line 65

Notice: Undefined index: command in /var/www/html/controller.php on line 70

Notice: Undefined index: command in /var/www/html/controller.php on line 77

Notice: Undefined index: command in /var/www/html/controller.php on line 99

Notice: Undefined index: command in /var/www/html/controller.php on line 111

Notice: Undefined index: command in /var/www/html/controller.php on line 116

Notice: Undefined index: command in /var/www/html/controller.php on line 124

Notice: Undefined index: command in /var/www/html/controller.php on line 133

Notice: Undefined index: command in /var/www/html/controller.php on line 146

Notice: Undefined index: command in /var/www/html/controller.php on line 150

Notice: Undefined index: command in /var/www/html/controller.php on line 156

Notice: Undefined index: command in /var/www/html/controller.php on line 163

Notice: Undefined index: command in /var/www/html/controller.php on line 308

Notice: Undefined index: command in /var/www/html/controller.php on line 319

Notice: Undefined index: command in /var/www/html/controller.php on line 324

Notice: Undefined index: command in /var/www/html/controller.php on line 329

Notice: Undefined index: command in /var/www/html/controller.php on line 334

Notice: Undefined index: command in /var/www/html/controller.php on line 346

Notice: Undefined index: command in /var/www/html/controller.php on line 355

Notice: Undefined index: command in /var/www/html/controller.php on line 367

Notice: Undefined index: command in /var/www/html/controller.php on line 422
mysqli error: Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'score_center_db.E.NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Fatal error: Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/html/controller.php:3594 Stack trace: #0 /var/www/html/controller.php(498): loadSlideShow('', Object(mysqli)) #1 {main} thrown in /var/www/html/controller.php on line 3594

**Comment by oschwartz10612** [comment]
I found a new issue:

In user_detail.php when you are editing a user, under Roles the following is displayed for all users:

'; }	?>
'.$role.'

Hopefully this has been helpful to update the system for newer MySql and PHP versions and not painfully annoying.

**Comment by Prestonjf** [comment]
Thanks for the update. I should be able to fix that query from controller.php and get back to you tomorrow morning. I will look into the user_detail.php issue by then as well.

**Comment by oschwartz10612** [comment]
Great, thanks!

**Comment by oschwartz10612** [comment]
I think this is related to the slideshow issue:

If I click Awards.pdf next to the events I get the following error:

Notice: Undefined index: command in /var/www/html/controller.php on line 65

Notice: Undefined index: command in /var/www/html/controller.php on line 70

Notice: Undefined index: command in /var/www/html/controller.php on line 77

Notice: Undefined index: command in /var/www/html/controller.php on line 99

Notice: Undefined index: command in /var/www/html/controller.php on line 111

Notice: Undefined index: command in /var/www/html/controller.php on line 116

Notice: Undefined index: command in /var/www/html/controller.php on line 124

Notice: Undefined index: command in /var/www/html/controller.php on line 133

Notice: Undefined index: command in /var/www/html/controller.php on line 146

Notice: Undefined index: command in /var/www/html/controller.php on line 150

Notice: Undefined index: command in /var/www/html/controller.php on line 156

Notice: Undefined index: command in /var/www/html/controller.php on line 163

Notice: Undefined index: command in /var/www/html/controller.php on line 308

Notice: Undefined index: command in /var/www/html/controller.php on line 319

Notice: Undefined index: command in /var/www/html/controller.php on line 324

Notice: Undefined index: command in /var/www/html/controller.php on line 329

Notice: Undefined index: command in /var/www/html/controller.php on line 334

Notice: Undefined index: command in /var/www/html/controller.php on line 346

Notice: Undefined index: command in /var/www/html/controller.php on line 355

Notice: Undefined index: command in /var/www/html/controller.php on line 367

Notice: Undefined index: command in /var/www/html/controller.php on line 422

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file in /var/www/html/libs/fpdf/fpdf.php:278 Stack trace: #0 /var/www/html/libs/fpdf/fpdf.php(1058): FPDF->Error('Some data has a...') #1 /var/www/html/libs/fpdf/fpdf.php(1007): FPDF->_checkoutput() #2 /var/www/html/controller.php(2453): FPDF->Output('D', 'MissionPossible...', true) #3 /var/www/html/controller.php(459): generateEventAwards(Object(mysqli), '1') #4 {main} thrown in /var/www/html/libs/fpdf/fpdf.php on line 278

**Comment by oschwartz10612** [comment]
I fixed the role output issue with a <?php replacing <?

Let me know and I can make a pull request if your code and mine don't line up from all of these changes. I can remove all of the error logging.

**Comment by oschwartz10612** [comment]
Sorry for the barrage of comments, but the export schedule button shows the following error:

Fatal error: Uncaught Exception: FPDF error: Some data has already been output, can't send PDF file (output started at /var/www/html/controller.php:647) in /var/www/html/libs/fpdf/fpdf.php:278 Stack trace: #0 /var/www/html/libs/fpdf/fpdf.php(1047): FPDF->Error('Some data has a...') #1 /var/www/html/libs/fpdf/fpdf.php(1007): FPDF->_checkoutput() #2 /var/www/html/functions/self_schedule_functions.php(674): FPDF->Output('D', 'Robinson_Schedu...', true) #3 /var/www/html/controller.php(769): exportScheduleOverview() #4 {main} thrown in /var/www/html/libs/fpdf/fpdf.php on line 278

**Comment by Prestonjf** [comment]
No worries about all the comments. I have some other priorities to work on, so I get to this when I can.
I believe all of the "FPDF" errors are related to the same thing. I will look into that next.

I have updated the "<?" in user_detail.php and commited that to the repository.

I have updated the queries in Controller.php which will hopefully allow the view slideshow to work. The error handling has been removed, so we might need to add that back in if "View Slideshow" still does not work. Let me know.

```
error_reporting(E_ALL);
ini_set('display_errors', 'On');
```

**Comment by oschwartz10612** [comment]
Viewing the slideshow and downloading it now works! Viewing the awards for each event also now works!

Unfortunately, the "Export Results .xlsx" button does not work. If I put the error handeling in controller.php I get the following error in the downloaded .xlsx file:

<b>Fatal error</b>:  'break' not | in the 'loop' or 'switch' context in <b>/var/www/html/libs/PHPExcel/Calculation/Functions.php</b> | on | line | <b>581</b><br | />

**Comment by Prestonjf** [comment]
More Progress! That is great!

Score Center uses the PHPExcel library when generating Excel files. I was reading the documentation on dependent PHP modules (extensions) for this library. It looks like there are a couple modules I should have had you turn on along with the bz2 and zip. 

In addition, can you also install/enable these PHP modules, then restart your server or httpd:
- xml
- gd

Then try the "Export Results" again.

**Comment by oschwartz10612** [comment]
Okay. I have had xml and gd installed for some time after I installed all of the libraries you had. See attached info.php.
[phpinfo().pdf](https://github.com/Prestonjf/scorecenter/files/2766131/phpinfo.pdf)

**Comment by oschwartz10612** [comment]
Also, with the new controller.php I am getting 502 Bad Gateway when I try to save settings on a tournament. 

It also appears that the Completed checkbox appears automatically now! :}

**Comment by Prestonjf** [comment]
I will look into the Exporting the Excel file more.

Try removing the error handling from Controller.php and let me kno if you still get the error when saving the "Manage Tournament" screen. I think that might be preventing some functionality.

**Comment by oschwartz10612** [comment]
The error handling is not in controller.php any more. I think this is a new issue.

**Comment by oschwartz10612** [comment]
Also apparently the old error with the slideshow etc still appears when logged in as an admin.

**Comment by Prestonjf** [comment]
I updated the entire PHPExcel library in the repository to the newest version 1.8.2. Please update your code with the new:
scorecenter/libs/PHPExcel.php
scorecenter/libs/PHPExcel/ (entire directory)

Some future bad news is that PHPExcel project is now deprecated, so going forward I will have to utilize a new library, but I am hoping this works for you.

**Comment by oschwartz10612** [comment]
Success with PHPExcel! Good luck finding a replacement.

So it is just the FPDF errors and 502 Bad Gateway. At least for now. XD

Thanks for the help!

**Comment by oschwartz10612** [comment]
Wait you fixed FPDF. My apologies.

**Comment by oschwartz10612** [comment]
This is the last 30 lines of the nginx error.log file if that helps:
[error.log](https://github.com/Prestonjf/scorecenter/files/2766624/error.log)

**Comment by oschwartz10612** [comment]
Nginx error.log file if it helps:
[error.log](https://github.com/Prestonjf/scorecenter/files/2766630/error.log)

**Comment by Prestonjf** [comment]
Thanks for the error logs! It looks like a possible cause could be some nginx configurations being set to small and the request requires a bigger buffer. Try changing the following properties in the nginx.conf file. Maybe at /etc/nginx/nginx.conf and restarting the server/httpd.

fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;

**Comment by oschwartz10612** [comment]
It appears that it is fixed! Thank you!

Apparently, the old error with the slideshow etc still appears when logged in as an Admin. I forgot to mention that earlier, sorry.

**Comment by oschwartz10612** [comment]
Wait it is working now. I don't know what was going on before.

I guess I will close this issue now. If I find anything else I will open a new one to keep it cleaner.

Thank you again for all of your help. I am going to introduce it to some people today and see what their reaction is.

Owen

**Comment by Prestonjf** [comment]
Thank you for taking the time to install the application and find these issues! You will have made it much easier for additional people to setup score center. I will be updating the readme on this repo to reflect the software requirements and PHP configurations needed. I hope your demonstration goes well!
